name = "Quasar"
uuid = "1b0303c1-8819-4d1c-a929-91cb710ac874"
authors = ["Kareem Fareed"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[extensions]
QuasarReactantExt = "Reactant"

[compat]
Distributions = "0.25.123"
ForwardDiff = "1.3.2"
julia = "1.11"
